"""Shared helpers for every ViGov hook.

WHY THIS FILE EXISTS: brain v1 loaded hooks with `exec(open(...).read())`, so hooks could
not import each other. The result: `_utf8_streams()` copied 7 times, `read_input()` 7 times,
the PII pattern twice. Fixing one pattern meant remembering every copy, and missing one was
invisible.

v2 invokes hooks directly (`python .claude/hooks/<name>.py`), so imports work. Every shared
pattern lives here — one place to fix.

Constraints: standard library only. A broken hook must NEVER block work — wrap everything.
"""

from __future__ import annotations

import datetime
import json
import os
import re
import sys

# --------------------------------------------------------------------------
# I/O
# --------------------------------------------------------------------------

def utf8_streams() -> None:
    """Force UTF-8 on all three standard streams. Call this first in every main().

    stdout/stderr: Windows terminals default to cp1252 and cannot PRINT Vietnamese, which
    kills a hook with UnicodeEncodeError.

    stdin: the more dangerous one, and it was missing until 2026-09-17. The payload arrives as
    UTF-8 bytes; cp1252 decodes almost all of them WITHOUT raising, so `json.load` succeeds and
    hands back content where every Vietnamese character has become mojibake. No error, no
    warning — just different text. Every hook rule that matches Vietnamese was therefore
    partially blind on the platform this project is developed on, and blind in the way that
    only ever produces silence: the guard reads a string that never matches and passes.

    Found through doc_guard: a second file claiming an existing `owns_facts` entry was not
    detected, because the fact arriving over stdin no longer equalled the fact read from disk
    with an explicit encoding.
    """
    for stream in (sys.stdin, sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def read_input() -> dict:
    try:
        return json.load(sys.stdin)
    except Exception:
        return {}


def tool_of(data: dict) -> str:
    return data.get("tool_name") or data.get("tool") or ""


def input_of(data: dict) -> dict:
    return data.get("tool_input") or data.get("input") or {}


def path_of(tool_input: dict) -> str:
    p = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    return p.replace("\\", "/")


def new_content(tool_input: dict) -> str:
    """Only the text about to be written — never the text being replaced."""
    if "content" in tool_input:
        return tool_input.get("content") or ""
    parts: list[str] = []
    if tool_input.get("new_string") is not None:
        parts.append(tool_input.get("new_string") or "")
    for edit in tool_input.get("edits") or []:
        parts.append(edit.get("new_string") or "")
    return "\n".join(parts)


def project_root(start: str | None = None) -> str:
    d = os.path.abspath(start or os.getcwd())
    for _ in range(6):
        if os.path.isdir(os.path.join(d, ".claude")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    return os.path.abspath(start or os.getcwd())


# --------------------------------------------------------------------------
# Skip zones
# --------------------------------------------------------------------------

SKIP_FRAGMENTS = (
    "/test/", "/tests/", "/testdata/", "/fixtures/", "/mocks/", "/__mocks__/",
    "/node_modules/", "/vendor/", "/dist/", "/build/", "/.git/", "/.claude/",
    "/kb/90-ephemeral/", "_test.go", ".spec.", ".test.",
    # The hooks' own self-test. It must CONTAIN the dangerous patterns — that is what it
    # tests. Without this exemption a guard blocks the very case that proves it works, and
    # the block case can never be written down.
    "tools/test_hooks.py",
)

# Paths that are genuinely produced by a generator. This is a PATH list on purpose.
#
# WHY NOT A CONTENT MARKER: until 2026-09-16 this was a content check — any file whose
# first 400 chars said "Code generated by" was exempted from EVERY content hook. That is a
# one-line universal opt-out: prepend one comment and tenant_scope_guard, pii_guard,
# secret_scan, rbac_guard, audit_guard, citizen_scope_guard, service_boundary_guard and
# data_safety_guard all stop looking. An agent writing the marker is exactly the case the
# hooks exist for, so the marker cannot be the thing that grants the exemption.
#
# A path cannot be forged by the content being written, so the decision moved here.
GENERATED_PATHS = (
    ".pb.go", "_grpc.pb.go", ".pb.gw.go", ".connect.go", "_pb2.py", ".gen.go",
    "/kb/20-contracts/", "/kb/30-indexes/",
)

# Kept only as a SECONDARY signal on an already-generated path (see is_generated).
GENERATED_MARKS = (
    "// Code generated by", "/* Code generated by", "# Code generated by",
    "DO NOT EDIT", "@generated",
)


def should_skip(path: str) -> bool:
    norm = path.replace("\\", "/").lower()
    return any(f in norm for f in SKIP_FRAGMENTS)


def is_generated(content: str, path: str = "") -> bool:
    """True only when the FILE PATH is a generated location.

    `content` is accepted for backwards compatibility and is deliberately NOT trusted on
    its own: a marker in the text being written is attacker-controlled (see GENERATED_PATHS).
    With no path given, nothing is exempt.
    """
    norm = (path or "").replace("\\", "/").lower()
    return any(g in norm for g in GENERATED_PATHS)


# --------------------------------------------------------------------------
# Shared patterns — FIX IN ONE PLACE
# --------------------------------------------------------------------------

# Fields carrying citizen personal data or auth secrets (rule 3)
PII_TOKEN = (
    r"(?:citizenPhone|CitizenPhone|applicantPhone|phoneNumber|soDienThoai|"
    r"\bphone\b|\bPhone\b|cccd|CCCD|cmnd|canCuoc|identityNumber|idNumber|"
    r"\botp\b|\bOTP\b|otpCode|maXacThuc|password|Password|passwordHash|matKhau|"
    r"accessToken|refreshToken|bearer|Bearer|sessionId|fullName|hoTen|diaChi|address)"
)

# Logging calls in Go and TS/JS
LOG_CALL = (
    r"(?:log\.(?:Print|Printf|Println|Debug|Info|Warn|Error|Fatal)\w*|"
    r"logger\.(?:Debug|Info|Warn|Error|Fatal)\w*|slog\.(?:Debug|Info|Warn|Error)|"
    r"fmt\.(?:Print|Printf|Println|Sprintf)|"
    r"console\.(?:log|info|warn|error|debug|trace))"
)

# Real Vietnamese mobile numbers (current prefixes)
VN_PHONE = r"[\"'`]0(?:3[2-9]|5[2689]|7[06-9]|8[1-9]|9[0-9])\d{7}[\"'`]"

# 12-digit national ID
VN_CCCD = r"[\"'`]0\d{11}[\"'`]"

# Agreed fake numbers for examples — not real personal data
SAFE_FAKE = re.compile(r"^0(?:9|3|7|8|5)0{6,9}\d?$")


# --------------------------------------------------------------------------
# Blocking and the guard log
# --------------------------------------------------------------------------

def log_guard(hook: str, tool: str, path: str, label: str, count: int = 1) -> None:
    """Append ONE line to .claude/logs/guard.jsonl.

    Records the violation LABEL and never the violating content — the guard log must not
    become a store of exactly what it just blocked.
    """
    try:
        d = os.path.join(project_root(), ".claude", "logs")
        os.makedirs(d, exist_ok=True)
        rec = {
            "at": datetime.datetime.now().isoformat(timespec="seconds"),
            "hook": hook,
            "tool": tool,
            "file": os.path.basename(path) if path else "",
            "label": label,
            "hits": count,
        }
        with open(os.path.join(d, "guard.jsonl"), "a", encoding="utf-8") as f:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    except Exception:
        pass


def block(hook: str, title: str, details: list[str], tail: list[str],
          tool: str = "", path: str = "") -> None:
    """Block: message on stderr + exit(2).

    The message MUST state the correct alternative. Blocking without pointing the way just
    sends the agent looking for another route — that is how enforcement layers die.
    """
    utf8_streams()
    msg = ["", f"[ViGov · BLOCKED] {title}"]
    msg += [f"  - {d}" for d in details[:6]]
    if len(details) > 6:
        msg.append(f"  ... and {len(details) - 6} more")
    msg += [""] + tail
    print("\n".join(msg), file=sys.stderr)
    log_guard(hook, tool, path, title, len(details))
    sys.exit(2)


def warn(hook: str, title: str, details: list[str], tail: list[str],
         tool: str = "", path: str = "") -> None:
    """Advise (PostToolUse): also exit(2), so the message enters the agent's context."""
    utf8_streams()
    msg = ["", f"[ViGov] {title}"]
    msg += [f"  - {d}" for d in details[:8]]
    if len(details) > 8:
        msg.append(f"  ... and {len(details) - 8} more")
    msg += [""] + tail
    print("\n".join(msg), file=sys.stderr)
    log_guard(hook, tool, path, title, len(details))
    sys.exit(2)
