// Code generated by tools/ingress from deploy/hosts.yaml. DO NOT EDIT.
//
// GENERATED — do not edit, source deploy/hosts.yaml. Regenerate: `go run ./tools/ingress` (or `make kb`).
//
// A changed value here changes which commune domains are reserved, and the SQL CHECK in
// migrations/0007_tenant_domain_khong_danh_rieng.sql cannot follow it: it needs a NEW migration,
// and TestLuatTenMienDanhRiengGoVaSQLKhop is red until it exists.

package domain

// platformWebRoots are the parents of each environment's commune web hosts (`*.<root>`),
// most specific first: a host is cut by the first root it ends with.
var platformWebRoots = []string{"stg.vigov.vn", "vigov.vn"}

// platformAPISuffixes are the per-environment suffixes of the service API hosts,
// `<service>.<suffix>`, in deploy/hosts.yaml order.
var platformAPISuffixes = []string{"api.vigov.vn", "api-stg.vigov.vn"}
