package main

import (
	"fmt"
	"sort"
	"strings"
)

// duongTepTS is the routing table the admin web reads to reverse-proxy /api/v1/* to the
// owning Go service. The Ingress sends ALL of <xa>.vigov.vn to web-admin (one "/" rule, owner's
// domain model of 2026-09-26), so this file — not ingress.yaml — is what decides which service
// answers an admin request.
//
// Its header still says "same resolved rules as ingress.yaml … same longest-first order". Since
// ingress.yaml carries one host per service instead of path rules that is only true of the
// comments there; the text is left alone because changing it would change a file web-admin
// ships, for no routing difference.
//
// It is rendered from the SAME resolved []luatIngress as ingress.yaml, never from a second
// reading of the contract: two resolvers are two answers to "who owns this path", and the day
// they disagree one surface routes a request to a service that does not own the data.
const duongTepTS = "web-admin/src/lib/api/dinh-tuyen.gen.ts"

// sinhTS renders the TypeScript table. The "/" catch-all is excluded: it is not an API route,
// and a proxy that forwarded "/" anywhere would forward every page of the web app.
//
// FAIL CLOSED: no API rule, or a value that would need escaping inside a TS string literal,
// stops the generator. Neither can come from a well-formed contract, so either one means the
// input is not what this code understands — and escaping it "correctly" would ship a table
// nobody has read.
func sinhTS(luats []luatIngress) ([]byte, error) {
	var api []luatIngress
	dichVu := map[string]bool{}
	for _, l := range luats {
		if l.BatHet {
			continue
		}
		if !chuoiAnToanTS(l.Duong) || !chuoiAnToanTS(l.DichVu) {
			return nil, fmt.Errorf("luật %q → %q có ký tự ngoài [a-z0-9/_-] — không đưa vào chuỗi TypeScript", l.Duong, l.DichVu)
		}
		if l.Duong != "/" && strings.HasSuffix(l.Duong, "/") {
			return nil, fmt.Errorf("luật %q kết thúc bằng `/` — tienTo phải không có gạch chéo cuối", l.Duong)
		}
		api = append(api, l)
		dichVu[l.DichVu] = true
	}
	if len(api) == 0 {
		// An empty table would make the proxy forward nothing — every admin API call 404.
		return nil, fmt.Errorf("không có luật API nào — không sinh %s rỗng", duongTepTS)
	}

	ten := make([]string, 0, len(dichVu))
	for d := range dichVu {
		ten = append(ten, d)
	}
	sort.Strings(ten)
	kieu := make([]string, len(ten))
	for i, d := range ten {
		kieu[i] = `"` + d + `"`
	}

	var b strings.Builder
	b.WriteString("// GENERATED by tools/ingress from kb/20-contracts/openapi.json — do not edit; regenerate with `go run ./tools/ingress` (or make kb).\n")
	b.WriteString("//\n")
	b.WriteString("// Same resolved rules as deploy/base/mang/ingress.yaml, minus the \"/\" catch-all, in the same\n")
	b.WriteString("// longest-first order. `tienTo` has no trailing slash; match it by PATH SEGMENT, not by\n")
	b.WriteString("// character: \"/api/v1/roles\" covers \"/api/v1/roles/7\" but NOT \"/api/v1/role-permissions\".\n")
	b.WriteString("// A path no entry covers must be refused, never sent to a default service (rule 1).\n")
	b.WriteString("export type DichVuAPI = " + strings.Join(kieu, " | ") + ";\n")
	b.WriteString("export const DINH_TUYEN_API: ReadonlyArray<{ readonly tienTo: string; readonly dichVu: DichVuAPI }> = [\n")
	for _, l := range api {
		b.WriteString(fmt.Sprintf("  { tienTo: \"%s\", dichVu: \"%s\" },\n", l.Duong, l.DichVu))
	}
	b.WriteString("] as const;\n")
	return []byte(b.String()), nil
}

// chuoiAnToanTS accepts only characters that need no escaping in a double-quoted TS literal
// and can occur in a resource prefix or a service name today.
func chuoiAnToanTS(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '/', r == '-', r == '_':
		default:
			return false
		}
	}
	return true
}
