package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Host constants generated from deploy/hosts.yaml — one file per consumer, so no consumer reads
// a host it did not ask for, and no consumer types one.
//
// WHY ONE FILE PER CONSUMER AND NOT ONE SHARED GO PACKAGE: service-platform's `domain/` imports
// the standard library and nothing else (every `*/internal/domain` in this repository does), so a
// `core/` package it would have to import is not an option there. With that consumer served by a
// file inside its own package, a shared package would have exactly one importer (core/config) —
// an abstraction for a single call site.
const (
	configHostsPath   = "core/config/hosts.gen.go"
	domainHostsPath   = "service-platform/internal/domain/hosts.gen.go"
	operatorHostsPath = "platform-admin/src/lib/server/host-plan.gen.ts"
	citizenHostsPath  = "citizen-app/src/cong-dan/api/service-hosts.gen.ts"

	// citizenServicesPath owns the list of services the citizen channel calls: `DichVuViGov`. The
	// generator reads that list instead of keeping a second copy of it.
	citizenServicesPath = "citizen-app/src/cong-dan/api/dia-chi-vigov.ts"
)

const generatedHeader = "GENERATED — do not edit, source deploy/hosts.yaml. Regenerate: `go run ./tools/ingress` (or `make kb`)."

// webRootsMostSpecificFirst returns the web roots ordered so a root that is a suffix of another
// ("vigov.vn" of "stg.vigov.vn") comes AFTER it. The consumers cut a host by the first root that
// matches; tried in the other order, "admin.stg.vigov.vn" would yield the label "admin.stg" under
// vigov.vn and miss the reserved-label table. More labels first is enough for that; ties keep
// the file's order.
func webRootsMostSpecificFirst(plan hostPlan) []string {
	roots := make([]string, 0, len(plan.Environments))
	for _, m := range plan.Environments {
		roots = append(roots, m.webRoot())
	}
	sort.SliceStable(roots, func(i, j int) bool {
		return strings.Count(roots[i], ".") > strings.Count(roots[j], ".")
	})
	return roots
}

func apiSuffixes(plan hostPlan) []string {
	out := make([]string, 0, len(plan.Environments))
	for _, m := range plan.Environments {
		out = append(out, m.DuoiAPI)
	}
	return out
}

func goStringList(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = fmt.Sprintf("%q", x)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func gofmtSource(path, src string) ([]byte, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("%s: mã sinh ra không qua gofmt: %w", path, err)
	}
	return out, nil
}

// renderConfigHosts — for parseOperatorHost (core/config/operator.go).
func renderConfigHosts(plan hostPlan) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/ingress from deploy/hosts.yaml. DO NOT EDIT.\n//\n")
	b.WriteString("// " + generatedHeader + "\n\n")
	b.WriteString("package config\n\n")
	b.WriteString("// platformWebRoots are the parents of each environment's commune web hosts (`*.<root>`),\n")
	b.WriteString("// most specific first: a host is cut by the first root it ends with.\n")
	b.WriteString("var platformWebRoots = " + goStringList(webRootsMostSpecificFirst(plan)) + "\n\n")
	b.WriteString("// platformRoot is the web root of the first environment — what deploy/base carries.\n")
	b.WriteString(fmt.Sprintf("const platformRoot = %q\n", plan.Environments[0].webRoot()))
	return gofmtSource(configHostsPath, b.String())
}

// renderDomainHosts — for LaTenMienDanhRieng (service-platform/internal/domain/ten_mien_danh_rieng.go).
func renderDomainHosts(plan hostPlan) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/ingress from deploy/hosts.yaml. DO NOT EDIT.\n//\n")
	b.WriteString("// " + generatedHeader + "\n")
	b.WriteString("//\n")
	b.WriteString("// A changed value here changes which commune domains are reserved, and the SQL CHECK in\n")
	b.WriteString("// migrations/0007_tenant_domain_khong_danh_rieng.sql cannot follow it: it needs a NEW migration,\n")
	b.WriteString("// and TestLuatTenMienDanhRiengGoVaSQLKhop is red until it exists.\n\n")
	b.WriteString("package domain\n\n")
	b.WriteString("// platformWebRoots are the parents of each environment's commune web hosts (`*.<root>`),\n")
	b.WriteString("// most specific first: a host is cut by the first root it ends with.\n")
	b.WriteString("var platformWebRoots = " + goStringList(webRootsMostSpecificFirst(plan)) + "\n\n")
	b.WriteString("// platformAPISuffixes are the per-environment suffixes of the service API hosts,\n")
	b.WriteString("// `<service>.<suffix>`, in deploy/hosts.yaml order.\n")
	b.WriteString("var platformAPISuffixes = " + goStringList(apiSuffixes(plan)) + "\n")
	return gofmtSource(domainHostsPath, b.String())
}

func tsStringList(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = `"` + x + `"`
	}
	return "[" + strings.Join(q, ", ") + "]"
}

// renderOperatorHosts — for operatorHost() (platform-admin/src/lib/server/operator-host.ts).
func renderOperatorHosts(plan hostPlan) []byte {
	var b strings.Builder
	b.WriteString("// " + generatedHeader + "\n")
	b.WriteString("//\n")
	b.WriteString("// Parents of each environment's commune web hosts (`*.<root>`), most specific first: a host is\n")
	b.WriteString("// cut by the first root it ends with — the same list and order core/config uses.\n")
	b.WriteString("export const PLATFORM_WEB_ROOTS: readonly string[] = " + tsStringList(webRootsMostSpecificFirst(plan)) + ";\n")
	return []byte(b.String())
}

// citizenServicesRe is the one line of dia-chi-vigov.ts the generator reads. Anything else in
// that shape-position — a multi-line union, a type alias of another type — is refused, not guessed.
var citizenServicesRe = regexp.MustCompile(`(?m)^export type DichVuViGov = ("[a-z][a-z0-9-]*"(?: \| "[a-z][a-z0-9-]*")*);\s*$`)

func readCitizenServices(root string) ([]string, error) {
	raw, err := os.ReadFile(filepath.Join(root, citizenServicesPath))
	if err != nil {
		return nil, fmt.Errorf("đọc %s: %w", citizenServicesPath, err)
	}
	m := citizenServicesRe.FindAllSubmatch(raw, -1)
	if len(m) != 1 {
		return nil, fmt.Errorf("%s: cần đúng MỘT dòng `export type DichVuViGov = \"a\" | \"b\";`, thấy %d", citizenServicesPath, len(m))
	}
	var out []string
	seen := map[string]bool{}
	for _, part := range strings.Split(string(m[0][1]), " | ") {
		s := strings.Trim(part, `"`)
		if seen[s] {
			return nil, fmt.Errorf("%s: dịch vụ %q khai hai lần trong DichVuViGov", citizenServicesPath, s)
		}
		seen[s] = true
		out = append(out, s)
	}
	return out, nil
}

// renderCitizenHosts — the per-service API hosts of `mini_app_environment` for the citizen Mini App
// (citizen-app/src/cong-dan/api/dia-chi-vigov.ts). A service the citizen channel names but the
// Ingress gives no host would be a call to a name nothing answers: refused here, at generation,
// instead of as a DNS failure on a citizen's phone.
func renderCitizenHosts(plan hostPlan, services []string, hosts []hostDichVu) ([]byte, error) {
	served := map[string]bool{}
	for _, h := range hosts {
		served[h.DichVu] = true
	}
	var b strings.Builder
	b.WriteString("// " + generatedHeader + "\n")
	b.WriteString("//\n")
	b.WriteString(fmt.Sprintf("// API hosts of environment `%s` (`mini_app_environment`) for exactly the services\n", plan.MiniApp.Ten))
	b.WriteString("// `DichVuViGov` in dia-chi-vigov.ts lists. The Mini App is built with prod hosts only (owner,\n")
	b.WriteString("// 01/10/2026).\n")
	b.WriteString("export const SERVICE_API_HOSTS = {\n")
	for _, s := range services {
		if !served[s] {
			return nil, fmt.Errorf("%s: DichVuViGov có %q nhưng Ingress không có host %s.%s — dịch vụ ấy không có tuyến REST",
				citizenServicesPath, s, s, plan.MiniApp.DuoiAPI)
		}
		b.WriteString(fmt.Sprintf("  %s: \"https://%s.%s\",\n", s, s, plan.MiniApp.DuoiAPI))
	}
	b.WriteString("} as const;\n")
	return []byte(b.String()), nil
}

// renderHostConstants returns the four generated host files keyed by repository-relative path.
func renderHostConstants(root string, plan hostPlan, luats []luatIngress) (map[string][]byte, error) {
	hosts, err := cacHostDichVu(luats)
	if err != nil {
		return nil, err
	}
	services, err := readCitizenServices(root)
	if err != nil {
		return nil, err
	}
	cfg, err := renderConfigHosts(plan)
	if err != nil {
		return nil, err
	}
	dom, err := renderDomainHosts(plan)
	if err != nil {
		return nil, err
	}
	cit, err := renderCitizenHosts(plan, services, hosts)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		configHostsPath:   cfg,
		domainHostsPath:   dom,
		operatorHostsPath: renderOperatorHosts(plan),
		citizenHostsPath:  cit,
	}, nil
}
