// Command kb generates the T2/T3 tiers of kb/ from the source code.
//
// WHY THIS EXISTS: hand-written documentation answering "where is X" and "who owns X" is
// wrong by the next day. Measured on the previous system: 38% of file paths cited in the docs
// pointed at files that no longer existed, and the hand-maintained technical-debt table said
// a helper lived in 3 places when it lived in 10.
//
// So those questions are answered by generation, and hand-written prose is reserved for the
// one question no tool can answer: WHY. See rule 9.
//
// Output is deliberately deterministic (sorted everywhere) so that regenerating produces no
// diff when nothing changed.
package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const header = "Code generated by tools/kb. DO NOT EDIT — run `make kb` to regenerate."

type serviceEntry struct {
	Name    string `json:"name"`
	Path    string `json:"path"`
	HasMain bool   `json:"has_main"`
	Summary string `json:"summary"`
}

type symbolEntry struct {
	Kind string `json:"kind"`
	At   string `json:"at"`
}

func main() {
	root, err := findRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "kb:", err)
		os.Exit(1)
	}

	services, err := scanServices(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "kb:", err)
		os.Exit(1)
	}
	symbols, err := scanSymbols(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "kb:", err)
		os.Exit(1)
	}

	out := filepath.Join(root, "kb", "30-indexes")
	write(out, "services.json", map[string]any{
		"_": header,
		"_description": "Every service, its path, and the one-line summary from its README. " +
			"Reasons for the boundaries live in kb/00-foundation/domain-boundaries.md.",
		"services": services,
	})
	write(out, "code-map.json", map[string]any{
		"_":            header,
		"_description": "Exported symbol -> file:line. USE THIS INSTEAD OF GREPPING THE REPO.",
		"symbols":      symbols,
	})

	// data-ownership and event-flows need real schemas and event registrations to be
	// meaningful. Emitting an honest empty index beats emitting a guess: a wrong ownership
	// map is worse than a missing one, because people act on it.
	ensurePlaceholder(out, "data-ownership.json",
		"entity -> owning service. Populated once services declare their schemas.",
		"no schemas defined yet")
	ensurePlaceholder(out, "event-flows.json",
		"event -> publisher, consumers, schema, supported versions.",
		"no events published yet")
	ensurePlaceholder(out, "dependencies.json",
		"call graph between services; used to detect synchronous dependency cycles.",
		"no inter-service calls yet")

	stampIndex(root)

	fmt.Printf("kb: %d services, %d exported symbols\n", len(services), len(symbols))
	fmt.Printf("kb: generated at %s\n", time.Now().Format(time.RFC3339))
}

// stampIndex fills the three metadata fields in kb/INDEX.yaml that the file itself declares
// as "`make kb` điền".
//
// WHY: until 2026-09-16 nothing wrote them, so generated_at / from_commit / in_use stayed
// null forever while the file claimed they were maintained. A file that documents its own
// freshness and is never actually stamped is worse than one that says nothing — it invites
// trust it has not earned.
//
// Only these three lines are rewritten; the rest of INDEX.yaml is hand-curated.
func stampIndex(root string) {
	path := filepath.Join(root, "kb", "INDEX.yaml")
	raw, err := os.ReadFile(path)
	if err != nil {
		return
	}

	commit := "unknown"
	if b, err := exec.Command("git", "-C", root, "rev-parse", "--short", "HEAD").Output(); err == nil {
		commit = strings.TrimSpace(string(b))
	}
	used := alwaysLoadTokens(root, string(raw))

	repl := map[string]string{
		"generated_at:": fmt.Sprintf("generated_at: %s", time.Now().UTC().Format(time.RFC3339)),
		"from_commit:":  fmt.Sprintf("from_commit: %s", commit),
		"in_use:":       fmt.Sprintf("  in_use: %d", used),
	}

	lines := strings.Split(string(raw), "\n")
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		for k, v := range repl {
			if strings.HasPrefix(t, k) {
				// keep any trailing comment on the line
				if idx := strings.Index(ln, "#"); idx >= 0 {
					v += "   " + strings.TrimSpace(ln[idx:])
				}
				lines[i] = v
			}
		}
	}
	_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
}

// alwaysLoadTokens estimates the always-loaded budget: the files listed under always_load,
// at the ~4 chars/token rule of thumb used by tools/check_brain.py.
func alwaysLoadTokens(root, index string) int {
	total := 0
	inList := false
	for _, ln := range strings.Split(index, "\n") {
		t := strings.TrimSpace(ln)
		if strings.HasPrefix(t, "always_load:") {
			inList = true
			continue
		}
		if inList {
			if !strings.HasPrefix(t, "- ") {
				if t != "" && !strings.HasPrefix(t, "#") {
					break
				}
				continue
			}
			f := strings.TrimSpace(strings.TrimPrefix(t, "- "))
			if b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(f))); err == nil {
				total += len(b)
			}
		}
	}
	return total / 4
}

func findRoot() (string, error) {
	d, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for i := 0; i < 6; i++ {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d, nil
		}
		parent := filepath.Dir(d)
		if parent == d {
			break
		}
		d = parent
	}
	return "", fmt.Errorf("go.mod not found — run from inside the repository")
}

func scanServices(root string) ([]serviceEntry, error) {
	dir := filepath.Join(root, "services")
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []serviceEntry
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		main := filepath.Join(dir, name, "cmd", "server", "main.go")
		_, mainErr := os.Stat(main)
		out = append(out, serviceEntry{
			Name:    name,
			Path:    "services/" + name,
			HasMain: mainErr == nil,
			Summary: readmeSummary(filepath.Join(dir, name, "README.md")),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// readmeSummary lifts the bolded Vietnamese unit name and description from the README, so the
// index carries the same words the humans use without anybody copying them by hand.
func readmeSummary(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "**") && strings.Contains(line, "—") {
			return strings.TrimSpace(strings.ReplaceAll(line, "**", ""))
		}
	}
	return ""
}

func scanSymbols(root string) (map[string]symbolEntry, error) {
	out := map[string]symbolEntry{}
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "node_modules", "vendor", "gen", "kb", ".claude":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, perr := parser.ParseFile(fset, path, nil, 0)
		if perr != nil {
			return nil // a file that does not parse is the compiler's problem, not ours
		}
		rel, _ := filepath.Rel(root, path)
		rel = filepath.ToSlash(rel)

		for _, decl := range f.Decls {
			switch dd := decl.(type) {
			case *ast.FuncDecl:
				if dd.Name.IsExported() {
					at := fmt.Sprintf("%s:%d", rel, fset.Position(dd.Pos()).Line)
					out[qualify(f.Name.Name, dd.Name.Name)] = symbolEntry{Kind: "func", At: at}
				}
			case *ast.GenDecl:
				for _, spec := range dd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}
					at := fmt.Sprintf("%s:%d", rel, fset.Position(ts.Pos()).Line)
					out[qualify(f.Name.Name, ts.Name.Name)] = symbolEntry{Kind: "type", At: at}
				}
			}
		}
		return nil
	})
	return out, err
}

func qualify(pkg, name string) string { return pkg + "." + name }

func write(dir, name string, v any) {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, "kb:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(dir, name), append(b, '\n'), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "kb:", err)
		os.Exit(1)
	}
}

// ensurePlaceholder writes an honest empty index, and never overwrites one that already has
// real content — the hand-curated transaction-boundaries index in particular must survive.
func ensurePlaceholder(dir, name, desc, empty string) {
	path := filepath.Join(dir, name)
	if b, err := os.ReadFile(path); err == nil && !strings.Contains(string(b), "_empty") {
		return
	}
	write(dir, name, map[string]any{
		"_":            header,
		"_description": desc,
		"_empty":       empty,
	})
}
