// GENERATED by tools/ingress from kb/20-contracts/openapi.json — do not edit; regenerate with `go run ./tools/ingress` (or make kb).
//
// Same resolved rules as deploy/base/mang/ingress.yaml, minus the "/" catch-all, in the same
// longest-first order. `tienTo` has no trailing slash; match it by PATH SEGMENT, not by
// character: "/api/v1/roles" covers "/api/v1/roles/7" but NOT "/api/v1/role-permissions".
// A path no entry covers must be refused, never sent to a default service (rule 1).
export type DichVuAPI = "comms" | "documents" | "finance" | "identity" | "petitions";
export const DINH_TUYEN_API: ReadonlyArray<{ readonly tienTo: string; readonly dichVu: DichVuAPI }> = [
  { tienTo: "/api/v1/capital-plan-categories", dichVu: "finance" },
  { tienTo: "/api/v1/residential-unit-types", dichVu: "identity" },
  { tienTo: "/api/v1/investment-projects", dichVu: "finance" },
  { tienTo: "/api/v1/content-categories", dichVu: "comms" },
  { tienTo: "/api/v1/incoming-documents", dichVu: "documents" },
  { tienTo: "/api/v1/my-citizen-reports", dichVu: "petitions" },
  { tienTo: "/api/v1/outgoing-documents", dichVu: "documents" },
  { tienTo: "/api/v1/budget-indicators", dichVu: "finance" },
  { tienTo: "/api/v1/residential-units", dichVu: "identity" },
  { tienTo: "/api/v1/swap-working-days", dichVu: "identity" },
  { tienTo: "/api/v1/role-permissions", dichVu: "identity" },
  { tienTo: "/api/v1/citizen-reports", dichVu: "petitions" },
  { tienTo: "/api/v1/map-asset-types", dichVu: "comms" },
  { tienTo: "/api/v1/public-holidays", dichVu: "identity" },
  { tienTo: "/api/v1/staff-directory", dichVu: "identity" },
  { tienTo: "/api/v1/task-priorities", dichVu: "petitions" },
  { tienTo: "/api/v1/budget-entries", dichVu: "finance" },
  { tienTo: "/api/v1/document-types", dichVu: "documents" },
  { tienTo: "/api/v1/announcements", dichVu: "comms" },
  { tienTo: "/api/v1/budget-sheets", dichVu: "finance" },
  { tienTo: "/api/v1/content-items", dichVu: "comms" },
  { tienTo: "/api/v1/disbursements", dichVu: "finance" },
  { tienTo: "/api/v1/task-statuses", dichVu: "petitions" },
  { tienTo: "/api/v1/working-hours", dichVu: "identity" },
  { tienTo: "/api/v1/budget-lines", dichVu: "finance" },
  { tienTo: "/api/v1/task-blocs", dichVu: "identity" },
  { tienTo: "/api/v1/task-types", dichVu: "petitions" },
  { tienTo: "/api/v1/org-units", dichVu: "identity" },
  { tienTo: "/api/v1/communes", dichVu: "identity" },
  { tienTo: "/api/v1/meetings", dichVu: "petitions" },
  { tienTo: "/api/v1/sessions", dichVu: "identity" },
  { tienTo: "/api/v1/roles", dichVu: "identity" },
  { tienTo: "/api/v1/staff", dichVu: "identity" },
  { tienTo: "/api/v1/tasks", dichVu: "petitions" },
  { tienTo: "/api/v1/sla", dichVu: "identity" },
] as const;
