/**
 * Tám tuyến của màn "Nội dung Mini App" (`docs/ui-ux/11-noi-dung-mini-app.md`), đúng bộ tuyến
 * `service-comms/internal/http/routes.go` khai — không nhiều hơn, không ít hơn.
 *
 *   GET   /api/v1/content-items                                   content.read
 *   GET   /api/v1/content-items/{id}                              content.read
 *   POST  /api/v1/content-items                                   content.update  + Idempotency-Key BẮT BUỘC
 *   PATCH /api/v1/content-items/{id}                              content.update  (không cần khoá chống trùng)
 *   POST  /api/v1/content-items/cover-images                      content.update  + Idempotency-Key BẮT BUỘC
 *   POST  /api/v1/content-items/cover-images/{id}/completion      content.update
 *   POST  /api/v1/content-items/audio-files                       content.update  + Idempotency-Key BẮT BUỘC (ADR 0067 §4)
 *   POST  /api/v1/content-items/audio-files/{id}/completion       content.update  {audio_duration_seconds}
 *   GET   /api/v1/content-categories                              content.read
 *   POST  /api/v1/content-categories                              content.update  + Idempotency-Key BẮT BUỘC
 *   PATCH /api/v1/content-categories/{id}                         content.update  (ADR 0067 §3)
 *   DELETE /api/v1/content-categories/{id}  {reason}              content.update  → 204 (soft delete)
 *
 * KHÔNG CÓ `DELETE` CHO MỘT MỤC NỘI DUNG, VÀ SỰ VẮNG MẶT ẤY LÀ MỘT CÂU TRẢ LỜI. §9 đề xuất một tuyến xoá; §6 chỉ vẽ
 * `✎`. Gỡ một bài khỏi Mini App là `PATCH` với `publish: false` — đúng như §7 tự mô tả ô tích của
 * nó. Không hàm nào ở đây dựng một đường `DELETE`: một hàm gọi vào tuyến không tồn tại là một hàm
 * biên dịch được, kiểm được bằng `fetch` giả, và 404 ở lần chạy thật.
 *
 * KIỂU LẤY TỪ HỢP ĐỒNG, KHÔNG GÕ TAY: `comms_noiDungRa`, `comms_themNoiDungVao`,
 * `comms_suaNoiDungVao`, `comms_danhMucRa`, `comms_danhSachDanhMucRa`, `comms_themDanhMucVao`,
 * `page_Result_comms_noiDungRa` đều đến từ `schema.gen.ts` (sinh từ `kb/20-contracts/openapi.json`).
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────
 * ⚠ HỢP ĐỒNG NAY KHAI ĐỦ BA THAM SỐ LỌC CỦA §6 — NHƯNG KHAI SAI LÀ BẮT BUỘC.
 *
 * `comms_get_content_items["truyVan"]` có `type` · `category` · `q` (`kb/20-contracts/openapi.json`,
 * tuyến `GET /api/v1/content-items`), đúng bộ tên handler đọc
 * (`service-comms/internal/http/noi_dung_mini_app.go:333-337`). Hợp đồng lại đánh dấu cả ba
 * `required: true`, trong khi handler coi một tham số VẮNG là "không lọc" — đó là lỗi của bộ sinh
 * hợp đồng, không phải của máy chủ. Gửi cả ba mỗi lần cho đúng kiểu là gửi `type=` rỗng, một hình
 * dạng màn hình không có lý do gì để dựa vào.
 *
 * Vì thế client KHÔNG dựng truy vấn theo kiểu `truyVan`: ba tên vẫn nằm trong ĐÚNG MỘT hàm
 * (`themLocVaoTruyVan`), chỉ gửi bộ lọc nào đang có giá trị, và `noi-dung.test.ts` vẫn đọc THẲNG
 * tệp Go để so lại từng tên — gõ `loai` thay `type` thì `tsc` im lặng, máy chủ bỏ qua và trả cả
 * quyển sổ trong khi cán bộ tin mình đang xem một lát cắt. Ngày hợp đồng khai ba tham số là tuỳ
 * chọn, hàm ấy là chỗ duy nhất phải sửa.
 *
 * A FOURTH, `status` (02/10/2026, C1), lives in the same function: the handler reads it and refuses an
 * unknown code with a 400. `schema.gen.ts` does not list it yet (regenerated by `make kb`), which is one
 * more reason the query is not built from `truyVan`.
 * ─────────────────────────────────────────────────────────────────────────────────────────────
 *
 * BỐN ĐIỀU MÁY CHỦ ĐÃ QUYẾT, VÀ MÔ-ĐUN NÀY KHÔNG VẼ KHÁC:
 *
 *   1. `body` VẮNG ở danh sách, CÓ ở chi tiết. Hợp đồng sinh ra `body?: string | null` đúng vì
 *      thế: `""` sẽ mang hai nghĩa — "bài này không có thân" và "bạn vừa hỏi một TRANG, mà trang
 *      thì không mang thân". Muốn toàn văn thì gọi `layMotNoiDung`, không suy từ danh sách.
 *   2. Không có `DELETE` — xem trên.
 *   3. `status` DO MÁY CHỦ QUYẾT từ ô tích `publish` của §7. Không thân nào ở đây mang `status`:
 *      một client tự khai trạng thái là một client đăng vượt qua bước duyệt mà §10.2 dành cho
 *      lượt đồng bộ.
 *   4. `view_count` không đi đâu cả. Hệ thống không đếm lượt xem (ADR 0047, người dùng bỏ cột
 *      01/10/2026): tuyến công khai của §9 đã dựng (`GET /api/v1/commune-news`) và cũng không tăng
 *      nó. Không đường ghi nào ở đây đụng tới nó, và màn không vẽ nó.
 *
 * KHÔNG CÓ `tenant_id` Ở BẤT KỲ ĐÂU — không thân, không query, không header. Xã suy từ `Host` ở
 * rìa ngoài cùng; client tự khai xã là client tự cấp quyền (luật 1, cấm #2).
 *
 * KHÔNG GHI LOG GÌ: `title`, `summary` và `body` là tin bài của xã, thường xuyên nhắc tên và hoàn
 * cảnh của một công dân cụ thể ("Trao quà cho gia đình ông …"). Chúng không được vào log, vào tên
 * tệp, vào URL hay vào khoá đệm (luật 3, cấm #1 và #4).
 */

import { CHUNG, docJSON, docThanKetQua, goiGhi, LOI_KHONG_RO, thongBaoLoi, type KetQua } from "./goi"; // vi-name-ok: existing exports of goi.ts (rule 12 inv 3)
import type { CallResult } from "./task-attachments";
import type {
  comms_audioFileOut,
  comms_audioUploadIn,
  comms_audioUploadOut,
  comms_coverFileOut,
  comms_coverUploadIn,
  comms_coverUploadOut,
  comms_danhMucRa,
  comms_deleteCategoryIn,
  comms_danhSachDanhMucRa,
  comms_get_content_categories,
  comms_get_content_items,
  comms_get_content_items_by_id,
  comms_noiDungRa,
  comms_patch_content_categories_by_id,
  comms_post_content_items_audio_files,
  comms_post_content_items_audio_files_by_id_completion,
  comms_post_content_items_cover_images,
  comms_post_content_items_cover_images_by_id_completion,
  comms_suaNoiDungVao,
  comms_themDanhMucVao,
  comms_themNoiDungVao,
  comms_updateCategoryIn,
  page_Result_comms_noiDungRa,
} from "./schema.gen";

/**
 * `comms_noiDungRa` plus `portal_category_name` (service-comms noi_dung_mini_app.go, 02/10/2026 C2):
 * on the list and the detail, ONLY for a synced item — the portal category it came in under.
 *
 * TODO(gen:api): `schema.gen.ts` predates the field, and `kb/20-contracts/openapi.json` is regenerated by
 * `make kb` after the backend lands. Once `comms_noiDungRa` carries it, this intersection is a no-op and
 * `portalCategoryName` can read the generated type directly. Optional on purpose: absent on a
 * hand-composed item (`omitempty`).
 */
export type ContentItemOut = comms_noiDungRa & { portal_category_name?: string };

/** The portal category of a synced item, `""` when there is none. */
export function portalCategoryName(nd: comms_noiDungRa): string {
  return (nd as ContentItemOut).portal_category_name ?? "";
}

/* ── Bộ lọc §6 ─────────────────────────────────────────────────────────────────────────────── */

/**
 * Ba bộ lọc của §6 cộng phân trang.
 *
 * TÊN THAM SỐ TRÊN DÂY LÀ TIẾNG ANH (`type` · `category` · `q`), không phải `loai`/`danh_muc` như
 * §9 phác: bề mặt hợp đồng dùng tiếng Anh (ADR 0011), và handler đọc đúng ba tên ấy.
 */
export type BoLocNoiDung = {
  /** Một trong sáu mã của §5. Rỗng/không có nghĩa là mọi loại. Mã lạ bị máy chủ trả 400. */
  loai?: string;
  /** ULID của danh mục. Rỗng nghĩa là `Tất cả danh mục`. */
  danhMucID?: string;
  /** Ô `🔍 Tìm theo tiêu đề…`. */
  tim?: string;
  /**
   * §6 status filter (`an` · `cho-duyet` · `dang-hien`), ANDed with the other three at the server
   * (02/10/2026, C1). Empty/absent = every status. An unknown code is the server's 400.
   */
  status?: string;
  limit?: number;
  /** `null` là trang đầu — xem `features/cau-hinh/ngan-xep-con-tro.ts`. */
  cursor?: string | null;
};

/**
 * Trần độ dài từ khoá tìm, đúng bằng trần máy chủ (`commsstore.TuKhoaTimToiDa`).
 *
 * Chép ở đây CHỈ để ô nhập dừng lại đúng chỗ máy chủ sẽ dừng — máy chủ vẫn là nơi từ chối thật,
 * và nó từ chối bằng một câu CỐ Ý không nhắc lại chữ người ta vừa gõ.
 */
export const TU_KHOA_TIM_TOI_DA = 200;

/**
 * BA CÁI TÊN CỦA §6 NẰM Ở ĐÚNG MỘT CHỖ — đây.
 *
 * Xem khối ⚠ ở đầu tệp: hợp đồng không khai chúng, nên không có kiểu nào canh. Gom vào một hàm để
 * ngày hợp đồng khai đủ thì chỉ phải sửa một chỗ, và để bài kiểm có đúng một nơi để đọc lại.
 */
function themLocVaoTruyVan(truyVan: URLSearchParams, loc: BoLocNoiDung): void {
  if (loc.loai !== undefined && loc.loai !== "") truyVan.set("type", loc.loai);
  if (loc.danhMucID !== undefined && loc.danhMucID !== "") truyVan.set("category", loc.danhMucID);
  if (loc.tim !== undefined && loc.tim !== "") truyVan.set("q", loc.tim);
  if (loc.status !== undefined && loc.status !== "") truyVan.set("status", loc.status);

  if (loc.limit !== undefined) truyVan.set("limit", String(loc.limit));
  // Con trỏ rỗng nghĩa là trang đầu. Gửi `cursor=` rỗng thì `page.Parse` trả 400 "con trỏ không
  // hợp lệ", nên trang đầu phải VẮNG tham số chứ không mang một tham số rỗng.
  if (loc.cursor !== undefined && loc.cursor !== null && loc.cursor !== "") {
    truyVan.set("cursor", loc.cursor);
  }
}

/**
 * Dựng đường dẫn sổ nội dung. Tách khỏi lời gọi mạng để kiểm được mà không cần thay `fetch`.
 *
 * KHÔNG GỬI `sort` VÀ `order`: máy chủ chỉ cho `created_at` và mặc định đã là giảm dần. Gửi lại
 * đúng giá trị mặc định chỉ thêm một chỗ có thể lệch.
 */
export function duongDanSoNoiDung(loc: BoLocNoiDung): string {
  const duongDan: comms_get_content_items["duongDan"] = "/api/v1/content-items";
  const truyVan = new URLSearchParams();
  themLocVaoTruyVan(truyVan, loc);
  const chuoi = truyVan.toString();
  return chuoi === "" ? duongDan : `${duongDan}?${chuoi}`;
}

/**
 * GET /api/v1/content-items — một trang của bảng §6.
 *
 * ⚠ CÁC HÀNG TRẢ VỀ KHÔNG MANG `body`. Đó là quyết định của máy chủ, không phải một thiếu sót:
 * một trăm bài ở trần thân bài là hai mươi triệu ký tự trong một phản hồi, còn §6 chỉ cần tiêu đề
 * và một dòng tóm tắt. Muốn toàn văn thì `layMotNoiDung`.
 */
export function laySoNoiDung(loc: BoLocNoiDung): Promise<KetQua<page_Result_comms_noiDungRa>> {
  return docJSON<page_Result_comms_noiDungRa>(duongDanSoNoiDung(loc));
}

/**
 * Đường dẫn một mục nội dung.
 *
 * `encodeURIComponent` CHỨ KHÔNG GHÉP THẲNG: id đến từ dữ liệu máy chủ trả, nhưng một id đi thẳng
 * vào đường dẫn là hình dạng mà ngày nào đó có người truyền vào một chuỗi do người dùng gõ.
 */
export function duongDanMotNoiDung(id: string): string {
  const mau: comms_get_content_items_by_id["duongDan"] = "/api/v1/content-items/{id}";
  return mau.replace("{id}", encodeURIComponent(id));
}

/** GET /api/v1/content-items/{id} — một mục KÈM toàn văn, cho modal sửa §7. */
export function layMotNoiDung(id: string): Promise<KetQua<comms_noiDungRa>> {
  return docJSON<comms_noiDungRa>(duongDanMotNoiDung(id));
}

/* ── Ghi ───────────────────────────────────────────────────────────────────────────────────── */

/**
 * The two §5 type codes that carry per-type fields (ADR 0047 §6, migration 0011 of service-comms).
 *
 * WHY THEY ARE NAMED HERE: the server refuses an event field on any type but `su-kien` and a video
 * link on any type but `video` with a 400. The request builders below read these, so the rule
 * "which field goes with which type" is written once on the client side.
 */
export const CONTENT_TYPE_EVENT = "su-kien";
export const CONTENT_TYPE_VIDEO = "video";
/** `link_to` and `display_order` go with this type only (migration 0012, ADR 0067 §5): 422 otherwise. */
export const CONTENT_TYPE_BANNER = "banner";
/** The audio file goes with this type only (ADR 0067 §4): 422 `audio_only_for_truyen_thanh` otherwise. */
export const CONTENT_TYPE_BROADCAST = "truyen-thanh";

/**
 * Copies the per-type fields that the chosen type can carry, and only when they hold a value.
 *
 * On a POST an empty string means "none" at the server, so omitting it is the same request with
 * one less key. A field the type cannot carry is left out instead of sent: sending it is a 400.
 */
function addTypeFieldsForCreate(out: ThemNoiDungVao, than: ThemNoiDungVao): void {
  if (than.type === CONTENT_TYPE_EVENT) {
    if (than.event_starts_at) out.event_starts_at = than.event_starts_at;
    if (than.event_ends_at) out.event_ends_at = than.event_ends_at;
    if (than.event_place) out.event_place = than.event_place;
  }
  if (than.type === CONTENT_TYPE_VIDEO && than.video_url) out.video_url = than.video_url;
  // Banner: an empty `link_to` is "not tappable", the same as absent; `display_order` absent = none.
  if (than.type === CONTENT_TYPE_BANNER) {
    if (than.link_to) out.link_to = than.link_to;
    if (than.display_order !== undefined && than.display_order !== null) {
      out.display_order = than.display_order;
    }
  }
}

/**
 * Thân của `POST /api/v1/content-items` — §7, trường theo trường. Bí danh của kiểu SINH RA.
 *
 * KHÔNG CÓ `status`, `source`, `source_ref` HAY `author_code`, và cả bốn là TỪ CHỐI CỦA MÁY CHỦ
 * chứ không phải bỏ sót. Trạng thái suy từ ô tích `publish`; nguồn gốc quyết định lượt đồng bộ sau
 * được làm gì với hàng (§10.4); tác giả là chủ thể của phiên (luật 6, bất biến 8). Một trường ở
 * đây cho bất kỳ thứ nào trong bốn là một client tự quyết một điều không thuộc về nó.
 *
 * KHÔNG CÓ `published_on`: §7 không có ô ngày. Bài soạn tay mang ngày hôm nay, do máy chủ đặt.
 */
export type ThemNoiDungVao = comms_themNoiDungVao;

/**
 * POST /api/v1/content-items — soạn một mục nội dung. 201, trả về cả hàng KÈM thân bài.
 *
 * `khoaChongTrung` LÀ THAM SỐ, KHÔNG SINH TẠI CHỖ. Hợp đồng đòi `Idempotency-Key` bắt buộc. Sinh
 * khoá bên trong hàm thì mỗi lần bấm lại sau một lỗi mạng là một khoá mới — tức đúng cái khoá
 * chống trùng sinh ra để chặn, vì lần gửi đầu CÓ THỂ đã tới máy chủ và đã đăng một bài lên Mini
 * App của cả xã. Khoá do biểu mẫu giữ, sống bằng đời một lần mở form.
 *
 * DỰNG TỪNG TRƯỜNG, KHÔNG `...than`: một phép trải ở đây là đường để một trường lạ đi lên máy chủ
 * vào ngày ai đó truyền vào một đối tượng vừa đọc được từ nơi khác — mà hàng đọc về CÓ mang
 * `status`, `source` và `view_count`.
 */
export function themNoiDung(
  than: ThemNoiDungVao,
  khoaChongTrung: string,
): Promise<KetQua<comms_noiDungRa>> {
  const duongDan: comms_get_content_items["duongDan"] = "/api/v1/content-items";

  const thanGui: ThemNoiDungVao = {
    type: than.type,
    title: than.title,
    category_id: than.category_id,
    summary: than.summary,
    body: than.body,
    image_url: than.image_url,
    publish: than.publish,
  };
  // An uploaded cover (`completeCoverUpload` answered `ready`). Omitted when none: on a POST an
  // absent id and an empty one mean the same, and the shorter body is the one with nothing to misread.
  if (than.cover_image_file_id) thanGui.cover_image_file_id = than.cover_image_file_id;
  // Event instants travel as RFC 3339 WITH an offset (`2026-10-05T08:00:00+07:00`); building them
  // from a datetime-local input is the form's job (`nhan-noi-dung.ts`). There is no `published_at`
  // in a request: ticking `publish` fixes it at the first publication and it never moves after.
  addTypeFieldsForCreate(thanGui, than);

  return goiGhi(duongDan, "POST", thanGui, 201, { "Idempotency-Key": khoaChongTrung }).then(
    docThanKetQua<comms_noiDungRa>,
  );
}

/**
 * Thân của `PATCH /api/v1/content-items/{id}` — §6 `✎` mở lại modal §7. Bí danh của kiểu SINH RA.
 *
 * ⚠ MỖI TRƯỜNG LÀ MỘT CON TRỎ Ở MÁY CHỦ, VÀ ĐÓ LÀ TOÀN BỘ LÝ DO ĐÂY LÀ `PATCH` CHỨ KHÔNG PHẢI
 * `PUT`. Mọi trường đều có một giá trị rỗng CÓ NGHĨA: `""` ở tóm tắt là "không có tóm tắt", `""`
 * ở danh mục là `— Chưa xếp danh mục —`, và `publish: false` là "gỡ khỏi Mini App". Một trường
 * VẮNG nghĩa là "để nguyên". Nên một trường `undefined` ở đây phải đi khỏi thân — `JSON.stringify`
 * làm đúng việc ấy — còn gửi `null` là gửi "để nguyên" bằng một cách khác, không phải "xoá".
 */
export type SuaNoiDungVao = comms_suaNoiDungVao;

/**
 * PATCH /api/v1/content-items/{id} — sửa một phần. 200, trả về hàng SAU khi sửa.
 *
 * KHÔNG MANG `Idempotency-Key`: hợp đồng không đòi, và một `PATCH` đặt lại đúng những giá trị ấy
 * hai lần cho ra cùng một hàng.
 *
 * PHẢN HỒI MANG `hand_edited`, VÀ ĐÓ LÀ NỬA NHÌN THẤY ĐƯỢC CỦA §10.4: cán bộ vừa sửa một bài đồng
 * bộ từ Cổng cần thấy rằng lần sửa ấy nay được bảo vệ khỏi lượt đồng bộ sau. Đây là chỗ duy nhất
 * màn hình biết được điều đó.
 */
export function suaNoiDung(id: string, than: SuaNoiDungVao): Promise<KetQua<comms_noiDungRa>> {
  const thanGui: SuaNoiDungVao = {
    type: than.type,
    category_id: than.category_id,
    title: than.title,
    summary: than.summary,
    body: than.body,
    image_url: than.image_url,
    publish: than.publish,
    // The per-type fields keep the PATCH meaning of every other field: absent = leave alone, "" =
    // CLEAR (the two instants included — the server has no other spelling of "clear"), value = set.
    //
    // NOT FILTERED BY TYPE HERE, unlike the POST: a PATCH often carries no `type`, so this function
    // cannot know the type after the edit. `thanSua` does, and only puts a field in when the
    // resulting type can carry it. Moving the type away clears the old type's fields server-side.
    event_starts_at: than.event_starts_at,
    event_ends_at: than.event_ends_at,
    event_place: than.event_place,
    video_url: than.video_url,
    // Absent = leave the cover alone; "" = DETACH (the server withdraws the public copy); an id = a
    // `ready` upload issued for THIS article (`content_item_id`). Passed through as given, `""` included.
    cover_image_file_id: than.cover_image_file_id,
    // Banner fields, same PATCH meaning: absent = leave alone; `link_to: ""` = not tappable any more.
    // `display_order` has NO clear on the wire (a JSON null reads as absent at the server), so a `null`
    // here would be a "leave alone" that looks like a clear — the form never builds one.
    link_to: than.link_to,
    display_order: than.display_order,
    // Broadcast audio (ADR 0067 §4): absent = leave alone; `audio_file_id: ""` = REMOVE (the server
    // clears both columns and retires the file). `thanSua` never sets either — attaching is the upload's
    // completion, removing is `removeContentAudio` — so a form Lưu cannot touch the audio by accident.
    audio_file_id: than.audio_file_id,
    audio_duration_seconds: than.audio_duration_seconds,
  };

  return goiGhi(duongDanMotNoiDung(id), "PATCH", thanGui, 200, undefined).then(
    docThanKetQua<comms_noiDungRa>,
  );
}

/* ── Ảnh bìa §7 — ADR 0052 §1, backend 606bf515 ───────────────────────────────────────────────
 *
 * Same three steps as the task attachments (`./task-attachments.ts`), and the middle step IS that
 * module's `uploadToStorage` — the bytes go STRAIGHT to the object store, never through this app (so
 * `proxy.ts`'s 10 MB body cap never applies: `/api/` is outside its matcher anyway, and the upload's
 * URL is the store's own origin).
 *
 *   a. `requestCoverUpload`   declare {file_name, content_type, size[, content_item_id]} → 201 form
 *   b. `uploadToStorage`      the presigned POST form, fields first, file last, no cookie
 *   c. `completeCoverUpload`  sniff, scan, derive the 1280 px copy → 200 `ready` | 422 | 409 | 503
 *
 * then the article carries `cover_image_file_id` on POST / PATCH.
 *
 * ⚠ `upload.url` + `upload.fields` ARE A BEARER CREDENTIAL: used in the one request they sign and
 * nowhere else — never logged, never kept in state past that request. `file_name` can name a person
 * (rule 3): it goes in the declaration body and nowhere else.
 */

export const COVER_FORM_MISSING =
  "Máy chủ không gửi kèm biểu mẫu tải lên cho ảnh này. Hãy chọn lại ảnh.";

async function readCallJSON<T>(res: Response, want: number): Promise<CallResult<T>> {
  if (res.status !== want) return { ok: false, status: res.status, message: await thongBaoLoi(res) };
  try {
    return { ok: true, data: (await res.json()) as T };
  } catch {
    return { ok: false, status: res.status, message: LOI_KHONG_RO };
  }
}

/**
 * a. Declare the cover. The server checks it against the platform's `content-image` policy (type,
 * size) and answers a refusal in one sentence, shown verbatim.
 *
 * `content_item_id` ONLY FOR AN ARTICLE ALREADY SAVED (the edit form). Absent for a new one: the
 * server reserves the article's id, and the POST that carries this upload's id creates it under that
 * id. Sending `""` would be a third spelling of "none", so an empty one is left out.
 *
 * `idempotencyKey`: ONE KEY PER ATTEMPT, minted by the caller — a replayed answer cannot carry the
 * signed form again (`core/idem` stores a code, not a body), so a retry is a new declaration.
 */
export async function requestCoverUpload(
  body: comms_coverUploadIn,
  idempotencyKey: string,
): Promise<CallResult<comms_coverUploadOut>> {
  const path: comms_post_content_items_cover_images["duongDan"] = "/api/v1/content-items/cover-images";
  // Field by field — never `...body`.
  const sent: comms_coverUploadIn = {
    file_name: body.file_name,
    content_type: body.content_type,
    size: body.size,
  };
  if (body.content_item_id) sent.content_item_id = body.content_item_id;
  try {
    const res = await fetch(path, {
      ...CHUNG,
      method: "POST",
      headers: { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey },
      body: JSON.stringify(sent),
    });
    const r = await readCallJSON<comms_coverUploadOut>(res, 201);
    if (r.ok && (r.data?.upload?.url === undefined || r.data.upload.fields === undefined || r.data.cover_image?.id === undefined)) {
      return { ok: false, status: 201, message: COVER_FORM_MISSING };
    }
    return r;
  } catch {
    return { ok: false, status: 0, message: LOI_KHONG_RO };
  }
}

/** c. Complete. Safe to repeat — a cover already `ready` answers itself again. */
export async function completeCoverUpload(id: string): Promise<CallResult<comms_coverFileOut>> {
  const template: comms_post_content_items_cover_images_by_id_completion["duongDan"] =
    "/api/v1/content-items/cover-images/{id}/completion";
  try {
    const res = await fetch(template.replace("{id}", encodeURIComponent(id)), { ...CHUNG, method: "POST" });
    return await readCallJSON<comms_coverFileOut>(res, 200);
  } catch {
    return { ok: false, status: 0, message: LOI_KHONG_RO };
  }
}

/* ── Truyền thanh §7 — ADR 0067 §4, backend 026ae398 ──────────────────────────────────────────
 *
 * The cover's three steps, for a broadcast's ONE audio file (MP3 / M4A, ≤ 30 MB, platform's
 * `content-audio` policy). Two differences, both the server's:
 *
 *   1. `content_item_id` is REQUIRED: the audio is uploaded for a SAVED `truyen-thanh` item (400
 *      otherwise, 422 `audio_only_for_truyen_thanh` when the saved type is another one).
 *   2. The completion carries the duration THE OFFICER TYPED (`audio_duration_seconds`, 1 .. 21600) —
 *      the server never measures it (ADR 0067 §4.1) — and ATTACHES the file to the item at once. There
 *      is no `audio_file_id` to send on Lưu.
 *
 * Removing is `PATCH … {audio_file_id: ""}` (`removeContentAudio`). Replacing = remove, then upload:
 * the item holds one file and a second declaration answers 409 `audio_limit`.
 *
 * The errors carry the server's `code` as well as its sentence: a 422 at completion is final for
 * `audio_rejected` (the bytes were refused) but NOT for `invalid_audio_duration` (the file is still
 * pending; correcting the duration and completing again is the way out). Both sentences are shown
 * verbatim; the code only decides which button the screen offers.
 *
 * ⚠ Same bearer-credential rule as the cover: `upload.url` + `upload.fields` are used in the one
 * request they sign and never logged; `file_name` can name a person (rule 3).
 */

/** A call's answer with the server's error `code` (`httpx.Error.code`), `""` when there is none. */
export type AudioCallResult<T> =
  | { readonly ok: true; readonly data: T }
  | { readonly ok: false; readonly status: number; readonly code: string; readonly message: string };

export const AUDIO_FORM_MISSING =
  "Máy chủ không gửi kèm biểu mẫu tải lên cho tệp âm thanh này. Hãy chọn lại tệp.";

async function readAudioJSON<T>(res: Response, want: number): Promise<AudioCallResult<T>> {
  if (res.status !== want) {
    let code = "";
    let message = LOI_KHONG_RO;
    try {
      const body = (await res.json()) as { code?: unknown; message?: unknown };
      if (typeof body?.code === "string") code = body.code;
      if (typeof body?.message === "string" && body.message !== "") message = body.message;
    } catch {
      // Not the server's httpx.Error (a proxy page): the generic sentence, no code.
    }
    return { ok: false, status: res.status, code, message };
  }
  try {
    return { ok: true, data: (await res.json()) as T };
  } catch {
    return { ok: false, status: res.status, code: "", message: LOI_KHONG_RO };
  }
}

/** a. Declare the audio for a SAVED broadcast. One Idempotency-Key per attempt (see the cover's). */
export async function requestAudioUpload(
  body: comms_audioUploadIn,
  idempotencyKey: string,
): Promise<AudioCallResult<comms_audioUploadOut>> {
  const path: comms_post_content_items_audio_files["duongDan"] = "/api/v1/content-items/audio-files";
  // Field by field — never `...body`.
  const sent: comms_audioUploadIn = {
    content_item_id: body.content_item_id,
    file_name: body.file_name,
    content_type: body.content_type,
    size: body.size,
  };
  try {
    const res = await fetch(path, {
      ...CHUNG,
      method: "POST",
      headers: { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey },
      body: JSON.stringify(sent),
    });
    const r = await readAudioJSON<comms_audioUploadOut>(res, 201);
    if (
      r.ok &&
      (r.data?.upload?.url === undefined || r.data.upload.fields === undefined || r.data.audio_file?.id === undefined)
    ) {
      return { ok: false, status: 201, code: "", message: AUDIO_FORM_MISSING };
    }
    return r;
  } catch {
    return { ok: false, status: 0, code: "", message: LOI_KHONG_RO };
  }
}

/**
 * c. Complete AND attach, with the typed duration. Safe to repeat: a file already `ready` answers itself
 * again — and then the duration sent is NOT applied (the server's rule; correcting it is a PATCH).
 */
export async function completeAudioUpload(
  id: string,
  durationSeconds: number,
): Promise<AudioCallResult<comms_audioFileOut>> {
  const template: comms_post_content_items_audio_files_by_id_completion["duongDan"] =
    "/api/v1/content-items/audio-files/{id}/completion";
  try {
    const res = await fetch(template.replace("{id}", encodeURIComponent(id)), {
      ...CHUNG,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ audio_duration_seconds: durationSeconds }),
    });
    return await readAudioJSON<comms_audioFileOut>(res, 200);
  } catch {
    return { ok: false, status: 0, code: "", message: LOI_KHONG_RO };
  }
}

/** `Gỡ âm thanh`: PATCH `{audio_file_id: ""}` — the server clears both columns and retires the file. */
export function removeContentAudio(id: string): Promise<KetQua<comms_noiDungRa>> {
  return suaNoiDung(id, { audio_file_id: "" });
}

/* ── Danh mục tin §6 ───────────────────────────────────────────────────────────────────────── */

/**
 * GET /api/v1/content-categories — cả cây danh mục của xã, PHẲNG.
 *
 * KHÔNG PHÂN TRANG, có chủ ý ở máy chủ: §7 vẽ một ô chọn và §3 vẽ một danh sách thụt đầu dòng, cả
 * hai cần trọn cây. Trần thay cho `limit` là `store.TranDanhMucMiniApp`.
 *
 * `parent_id` RỖNG LÀ GỐC. Cây trả về phẳng vì hai màn muốn hai hình dạng khác nhau của cùng một
 * bộ hàng — dựng cây là việc của bên hiển thị, không phải của tuyến.
 */
export function layDanhMucNoiDung(): Promise<KetQua<comms_danhSachDanhMucRa>> {
  const duongDan: comms_get_content_categories["duongDan"] = "/api/v1/content-categories";
  return docJSON<comms_danhSachDanhMucRa>(duongDan);
}

/** Thân của `POST /api/v1/content-categories`. Bí danh của kiểu SINH RA. */
export type ThemDanhMucVao = comms_themDanhMucVao;

/**
 * POST /api/v1/content-categories — thêm một danh mục. 201.
 *
 * `Idempotency-Key` BẮT BUỘC theo hợp đồng, cùng khuôn với `themNoiDung`: khoá do biểu mẫu giữ,
 * chỉ đổi khi đã ghi xong.
 *
 * MÁY CHỦ TRẢ 409 KHI SLUG ĐÃ DÙNG — KỂ CẢ KHI DANH MỤC MANG SLUG ẤY ĐÃ BỊ XOÁ. Câu 409 ấy nói rõ
 * lý do ("mã đã cấp thì không cấp lại"), và câu ấy đi thẳng ra màn hình chứ không được viết lại ở
 * đây: viết lại là dựng bản sao thứ hai của một quy tắc nghiệp vụ.
 */
export function themDanhMucNoiDung(
  than: ThemDanhMucVao,
  khoaChongTrung: string,
): Promise<KetQua<comms_danhMucRa>> {
  const duongDan: comms_get_content_categories["duongDan"] = "/api/v1/content-categories";

  const thanGui: ThemDanhMucVao = {
    name: than.name,
    slug: than.slug,
    parent_id: than.parent_id,
    order: than.order,
  };

  return goiGhi(duongDan, "POST", thanGui, 201, { "Idempotency-Key": khoaChongTrung }).then(
    docThanKetQua<comms_danhMucRa>,
  );
}

/** Path of one category, `{id}` encoded — same reason as `duongDanMotNoiDung`. */
export function contentCategoryPath(id: string): string {
  const template: comms_patch_content_categories_by_id["duongDan"] = "/api/v1/content-categories/{id}";
  return template.replace("{id}", encodeURIComponent(id));
}

/** Body of `PATCH /api/v1/content-categories/{id}`. Alias of the GENERATED type. */
export type UpdateCategoryIn = comms_updateCategoryIn;

/**
 * PATCH /api/v1/content-categories/{id} — name, parent (`""` = root), order, hidden. 200, the row after.
 *
 * FIELD BY FIELD, AND `slug` IS NEVER COPIED: the server refuses a body naming it (400, an issued code
 * never changes), so a caller that passed a whole row read back from the list would turn every edit into
 * a refusal. Absent = leave alone; `JSON.stringify` drops the `undefined` ones.
 *
 * No `Idempotency-Key`: the contract does not take one, and the use case writes nothing when nothing moved.
 */
export function updateContentCategory(
  id: string,
  body: UpdateCategoryIn,
): Promise<KetQua<comms_danhMucRa>> {
  const sent: UpdateCategoryIn = {
    name: body.name,
    parent_id: body.parent_id,
    order: body.order,
    hidden: body.hidden,
  };
  return goiGhi(contentCategoryPath(id), "PATCH", sent, 200, undefined).then(
    docThanKetQua<comms_danhMucRa>,
  );
}

/**
 * DELETE /api/v1/content-categories/{id} with `{reason}` — a SOFT delete (rule 7). 204, no body.
 *
 * THE REASON TRAVELS IN THE BODY, never in the URL: free text about a government record does not belong
 * in a query string that every access log keeps. 409 while the category still holds an article or a child
 * category; the server's sentence (which suggests hiding instead) reaches the screen as it came.
 */
export function deleteContentCategory(id: string, reason: string): Promise<KetQua<null>> {
  const sent: comms_deleteCategoryIn = { reason };
  return goiGhi(contentCategoryPath(id), "DELETE", sent, 204, undefined).then((kq) =>
    kq.ok ? { ok: true, duLieu: null } : kq,
  );
}
